import type { MDXComponents } from "mdx/types";

export const mdxComponents: MDXComponents = {
  h2: (props) => (
    <h2
      className="font-display text-3xl md:text-4xl uppercase tracking-wide text-marfil mt-12 mb-4 pb-2 border-b border-gris/30 scroll-mt-28"
      {...props}
    />
  ),
  h3: (props) => (
    <h3
      className="font-display text-xl md:text-2xl uppercase tracking-wide text-beige mt-8 mb-3 scroll-mt-28"
      {...props}
    />
  ),
  p: (props) => <p className="font-body text-base md:text-lg leading-relaxed text-beige/90 mb-5" {...props} />,
  a: (props) => (
    <a
      className="text-rojo underline underline-offset-2 hover:text-marfil transition-colors"
      {...props}
    />
  ),
  ul: (props) => (
    <ul className="font-body list-none mb-5 space-y-2 text-beige/90" {...props} />
  ),
  ol: (props) => (
    <ol className="font-body list-decimal pl-6 mb-5 space-y-2 text-beige/90" {...props} />
  ),
  li: (props) => (
    <li className="pl-4 border-l border-gris/30 ml-1" {...props} />
  ),
  blockquote: (props) => (
    <blockquote
      className="my-6 border-l-2 border-rojo bg-negro/40 px-5 py-4 font-body italic text-beige/80"
      {...props}
    />
  ),
  hr: () => <hr className="my-10 border-t border-gris/20" />,
  strong: (props) => <strong className="text-marfil font-semibold" {...props} />,
  table: (props) => (
    <div className="my-6 overflow-x-auto border border-gris/30">
      <table className="w-full font-mono text-sm" {...props} />
    </div>
  ),
  th: (props) => (
    <th
      className="border border-gris/30 bg-negro/60 px-3 py-2 text-left uppercase tracking-wide text-beige"
      {...props}
    />
  ),
  td: (props) => <td className="border border-gris/30 px-3 py-2 text-beige/80" {...props} />,
  // Footnotes generated by remark-gfm
  section: ({ className, ...props }: any) => {
    if (className === "footnotes") {
      return (
        <section
          className="footnotes mt-16 pt-6 border-t border-gris/30 font-body text-sm text-beige/70"
          {...props}
        />
      );
    }
    return <section className={className} {...props} />;
  },
};
